unit TestTaxNumber;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, TaxNumber, ITaxNumber, TaxNumberDigits, System.SysUtils;

type
  // Test methods for class TTaxNumber

  TestTTaxNumber = class(TTestCase)
  strict private
    FTaxNumber: TTaxNumber;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCheckTaxNumber;
    procedure TestCheckBusinessTaxNumber;
    procedure TestInvalidTaxNumber;
    procedure TestInvalidBusinessTaxNumber;
  end;

implementation

procedure TestTTaxNumber.SetUp;
begin
  FTaxNumber := TTaxNumber.Create(TTaxNumberDigits.Create);
end;

procedure TestTTaxNumber.TearDown;
begin
  FTaxNumber.Free;
  FTaxNumber := nil;
end;

procedure TestTTaxNumber.TestCheckTaxNumber;
var
  ReturnValue: Boolean;
  TaxNumber: string;
begin
  // Setup method call parameters
  TaxNumber := '726.218.380-06'; //generated form https://www.geradordecpf.org
  ReturnValue := FTaxNumber.CheckTaxNumber(TaxNumber);
  //Validate method results
  Assert(ReturnValue);
end;

procedure TestTTaxNumber.TestInvalidBusinessTaxNumber;
var
  ReturnValue: Boolean;
  TaxNumber: string;
begin
  //Setup method call parameters
  TaxNumber := '08.805.315/0001-10';
  ReturnValue := FTaxNumber.CheckBusinessTaxNumber(TaxNumber);
  //Validate method results
  Assert(not ReturnValue);
end;

procedure TestTTaxNumber.TestInvalidTaxNumber;
var
  ReturnValue: Boolean;
  TaxNumber: string;
begin
  // Setup method call parameters
  TaxNumber := '726.218.380-00';
  ReturnValue := FTaxNumber.CheckTaxNumber(TaxNumber);
  //Validate method results
  Assert(not ReturnValue);
end;

procedure TestTTaxNumber.TestCheckBusinessTaxNumber;
var
  ReturnValue: Boolean;
  TaxNumber: string;
begin
  //Setup method call parameters
  TaxNumber := '08.805.315/0001-18'; //generated form https://www.geradordecpf.org
  ReturnValue := FTaxNumber.CheckBusinessTaxNumber(TaxNumber);
  //Validate method results
  Assert(ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTTaxNumber.Suite);
end.

